Hotel project/TorquayHotel_root/TorquayHotel/urls.py
from django.contrib import admin
from django.urls import path, include
from visitors import urls
# from staff import urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('visitors/', include('visitors.urls')),
    # path('staff/', include('staff.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Hotel project/TorquayHotel_root/visitors/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'visitors'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('rooms/', views.rooms_page, name='rooms_page'),
    path('booking/', views.check_availability, name='check_availability'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', logout_view, name = 'logout'),
    path('profile/<int:user_id>/', profile_view, name='profile'),
    path('rooms/<int:category_id>/', views.category_view, name='category_view'),
    path('vacancies/', views.check_availability, name='vacancies'),
    path('rooms/', views.booking_room_view, name='booking_room_view'),
    path('reservation/', views.reservation, name='reservation_view'),
]

Hotel project/TorquayHotel_root/visitors/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
   
    def __str__(self):
        return f'Profile: {self.user.username}'



class Category(models.Model):
    name = models.CharField(max_length=100)
    price_per_night = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(null=True, blank=True)
    capacity = models.PositiveIntegerField() 

    def __str__(self):
        return self.name


class Room(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    room_number = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.category.name} - {self.room_number}"
    
    
class RoomAmenities(models.Model):
    name = models.CharField(max_length=100)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

    
class UpcomingEvents(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=100)
    suitable_for_children = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class GuestDetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    additional_details = models.TextField()

    def __str__(self):
        return self.user.username


class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    num_adults = models.PositiveIntegerField()
    num_kids = models.PositiveIntegerField(default=0)
    payment_status = models.CharField(max_length=20, default='Pending', choices=[('Paid', 'Paid'), ('Pending', 'Pending')])
    created_at = models.DateTimeField(auto_now_add=True)
    guest_details = models.OneToOneField(GuestDetails, on_delete=models.CASCADE, default=None)


    def __str__(self):
        return f"Booking for Room {self.room.category.name - self.room.room_number}"

    def get_total_price(self):
        num_nights = (self.check_out_date - self.check_in_date).days
        return self.room.category.price_per_night * num_nights  
    

class Child(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    age = models.PositiveIntegerField()  

    
    
    # @staticmethod #TODO: work on this
    # def check_availability(request, category_id):
    #     category = Category.objects.get(id=category_id)
    #     rooms = Room.objects.filter(category=category)# all the rooms of the specific category
    #     available_rooms = []

    #     for room in rooms:
    #         if not Booking.objects.filter(room=room).exists():#it means that there are no bookings associated with the current room.
    #             available_rooms.append(room)

    #         if available_rooms:
    #             available_room = available_rooms.first()
    #         # Mark the room as temporarily booked
    #         # You can set a flag or update a field on the room model to indicate its temporary booking status

    #             context = {'category': category, 'room': available_room}
    #         else:
    #             context = {'category': category, 'room': None}

    #     return available_room
    


# class Review(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     room = models.ForeignKey(Room, on_delete=models.CASCADE) #??
#     rating = models.PositiveIntegerField()
#     comment = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f"Review #{self.pk} by {self.user.username}"


# class Hotel(models.Model):
#     name = models.CharField(max_length=100)
#     address = models.CharField(max_length=200)
#     phone_number = models.CharField(max_length=20)
#     email = models.EmailField(max_length=100)
#     facebook_link = models.URLField(max_length=200, null=True, blank=True)
#     tiktok_link = models.URLField(max_length=200, null=True, blank=True)
#     instagram_link = models.URLField(max_length=200, null=True, blank=True)

#     def __str__(self):
#         return self.name

    

Hotel project/TorquayHotel_root/visitors/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.forms import AuthenticationForm
from .models import *


class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2']

class LoginForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = '__all__'
        

class CheckAvailabilityForm(forms.Form):
    check_in_date = forms.DateField()
    check_out_date = forms.DateField()
    num_adults = forms.IntegerField()
    num_kids = forms.IntegerField()   

    def __init__(self, *args, **kwargs):
        super(CheckAvailabilityForm, self).__init__(*args, **kwargs)
        num_kids = self.initial.get('num_kids', 0)
        for i in range(num_kids):
            field_name = f'child_age_{i+1}'
            label = f'Child {i+1} Age'
            self.fields[field_name] = forms.IntegerField(label=label)


class GuestDetailsForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

    class Meta:
        model = GuestDetails
        fields = ['first_name', 'last_name', 'phone', 'email', 'country', 'city', 'zip_code', 'additional_details']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(GuestDetailsForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['first_name'].initial = user.first_name
            self.fields['last_name'].initial = user.last_name


# class ReviewForm(forms.ModelForm):
#     class Meta:
#         model = Review
#         fields = ['rating', 'comment']

Hotel project/TorquayHotel_root/visitors/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from datetime import datetime
from django.urls import reverse
from django.urls import reverse_lazy
from .forms import *
from .models import *


def homepage(request):
    return render(request, 'test.html')

def rooms_page(request):
    return render(request, 'room.html')

def booking_room_view(request):
    return render(request, 'room.html')

def category_view(request, category_id):
    category = Category.objects.get(id=category_id)
    context = {'category': category}
    return render(request, 'category_details.html', context)# fix the names

def check_availability(request):

    if request.method == 'POST':
        form = CheckAvailabilityForm(request.POST)
        if form.is_valid():
            check_in_date = form.cleaned_data['check_in_date']
            check_out_date = form.cleaned_data['check_out_date']
            num_adults = form.cleaned_data['num_adults']
            num_kids = form.cleaned_data['num_kids']
            kid_ages = [request.POST.get('child_age_{}'.format(i + 1)) for i in range(num_kids)]
            kid_ages = [int(age) if age is not None else 0 for age in kid_ages]

            # Call the get_vacancies function and store the returned values in variables
            available_rooms = get_vacancies(check_in_date, check_out_date, num_adults, num_kids, kid_ages)

            kids_range = range(num_kids)  # Generate the range of numbers for kids' ages, because the range() function in Django templates doesn't accept dynamic variables like num_kids ( and i need to use in the template). 

            context = {
                'available_rooms': available_rooms,
                'check_in_date': check_in_date,
                'check_out_date': check_out_date,
                'num_adults': num_adults,
                'num_kids': num_kids, 
                'kids_range': kids_range,
                'kid_ages': kid_ages, 
            }

            
            return render(request, 'vacancies.html', context)

    form = CheckAvailabilityForm()   
    context = {'form': form}
    return render(request, 'booking.html', context)


def get_vacancies(check_in_date, check_out_date, num_adults, num_kids, kid_ages):
    """
    Get a list of available room options for the given date range and number of guests (one option per room category).
    """
    conflicting_bookings = Booking.objects.filter(
        Q(check_in_date__lt=check_out_date) & Q(check_out_date__gt=check_in_date)
    )
    booked_rooms = [booking.room for booking in conflicting_bookings]

    #Retrieve a list of room categories that are suitable for the specified number of guests.
    if num_kids == 1 and kid_ages[0] > 2:
        room_types = Category.objects.filter(
            Q(capacity__gte=num_adults + num_kids) |
            (Q(roomamenities__name='sofa bed') &
            Q(roomamenities__categories__capacity=num_adults + num_kids - 1))
        ).distinct()
    elif num_kids == 1 and kid_ages[0] <= 2:
        room_types = Category.objects.filter(
            (Q(capacity__gte=num_adults + num_kids)| Q(capacity__gte=num_adults))
        ).distinct() 
    else:
        room_types = Category.objects.filter(capacity__gte=num_adults + num_kids)

   # creating the result list of available rooms (categories)

    available_rooms = [room.category for room in Room.objects.all() if room.category in room_types and room not in booked_rooms]

    return available_rooms


def reservation(request):
    room_category = request.GET.get('room')
    category = get_object_or_404(Category, name=room_category)
    room = category
    check_in_date_str = request.GET.get('check_in_date')
    check_out_date_str = request.GET.get('check_out_date')
    num_adults = request.GET.get('num_adults')
    num_kids = request.GET.get('num_kids')
    kid_ages = request.GET.get('kid_ages')
    user = request.user

    if request.method == 'POST':
        guest_details_form = GuestDetailsForm(request.POST, user=user)
        if guest_details_form.is_valid():
            guest_details = guest_details_form.save(commit=False)
            guest_details.user = user
            guest_details.save()

            # retrieve the first available room of chosen category
            room = Room.objects.filter(category=category).first()

            # Create a booking object
            booking = Booking.objects.create(
                user=user,
                room=room,
                check_in_date = datetime.strptime(check_in_date_str, '%B %d, %Y').strftime('%Y-%m-%d'),
                check_out_date = datetime.strptime(check_out_date_str, '%B %d, %Y').strftime('%Y-%m-%d'),
                num_adults=num_adults,
                num_kids=num_kids,
                guest_details=guest_details
            )

            # Perform additional actions if needed

            return redirect('visitors:homepage')
    else:
        guest_details_form = GuestDetailsForm(user=user)

    context = {
        'room': room,
        'check_in_date': check_in_date_str,
        'check_out_date': check_out_date_str,
        'num_adults': num_adults,
        'num_kids': num_kids,
        'kid_ages': kid_ages,
        'user_name': user.first_name,
        'form': guest_details_form
    }

    return render(request, 'reservation.html', context)


class SignupView(CreateView):
    form_class = SignupForm
    template_name = 'signup.html'
    success_url = reverse_lazy('visitors:homepage')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']
        # Fetch the user with authenticate()
        authenticated_user = authenticate(username=username, password=password)
        if authenticated_user is not None:
            # Sign the user in using login()
            login(self.request, authenticated_user)
        return response
    

class CustomLoginView(LoginView):
    template_name = 'login.html'
    success_url = reverse_lazy('visitors:homepage') 
    

def profile_view(request, user_id):
    user = get_object_or_404(User, id=user_id)
    return render(request, 'visitors:homepage', {'user': user})    


def logout_view(request):
    logout(request)
    return redirect('visitors:homepage')


# def check_availability(request): # function handles the request to check the availability of a specific room
#     # Retrieve info from the request
#     check_in_date = request.POST.get('check_in_date')
#     check_out_date = request.POST.get('check_out_date')
#     num_guests = request.POST.get('num_guests') 

#     # Retrieve the room for which availability needs to be checked (e.g., based on room number or ID)
#     room_number = request.POST.get('room_number')
#     room = Room.objects.get(number=room_number)

#     # Check availability using the is_available method of the Booking model
#     is_available = room.is_available(check_in_date, check_out_date, num_guests)

#     # Render a response based on the availability status
#     return render(request, 'availability.html', {'is_available': is_available})


# def book_room(request, room_id):
#     room = Room.objects.get(id=room_id)

#     if request.method == 'POST':
#         form = BookingForm(request.POST)
#         if form.is_valid():
#             booking = form.save(commit=False)
#             booking.room = room
#             booking.user = request.user  # Assuming you have user authentication
#             booking.save()
#             return redirect('booking_success')
#     else:
#         form = BookingForm()

#     return render(request, 'book_room.html', {'form': form, 'room': room})



# def write_review(request, room_id):
#     room = get_object_or_404(Room, id=room_id)

#     booking = Booking.objects.filter(user=request.user, room=room).first()
#     if not booking:
#         # Redirect or show an error message indicating that only guests who have booked the room can write a review
#         return HttpResponse("Only guests who have booked this room can write a review.")

#     if request.method == 'POST':
#         form = ReviewForm(request.POST)
#         if form.is_valid():
#             review = form.save(commit=False)
#             review.user = request.user
#             review.room = room
#             review.save()
#             return redirect('room_detail', room_id=room.id)
#     else:
#         form = ReviewForm()

#     context = {
#         'room': room,
#         'booking': booking,
#         'form': form
#     }

#     return render(request, 'write_review.html', context)

Hotel project/TorquayHotel_root/visitors/templates/login.html
{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

Hotel project/TorquayHotel_root/visitors/templates/popup_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/vacancies.css' %}">
</head>
<body>
    <div class="container">
        <div class="welcome">
          <div class="pinkbox">
            <div class="signup nodisplay">
              <h1>register</h1>
              <form autocomplete="off">
                <input type="text" placeholder="username">
                <input type="email" placeholder="email">
                <input type="password" placeholder="password">
                <input type="password" placeholder="confirm password">
                <button class="button submit">create account </button>
              </form>
            </div>
            <div class="signin">
              <h1>sign in</h1>
              <form class="more-padding" autocomplete="off">
                <input type="text" placeholder="username">
                <input type="password" placeholder="password">
                <div class="checkbox">
                  <input type="checkbox" id="remember" /><label for="remember">remember me</label>
                </div>
      
                <button class="button submit">login</button>
              </form>
            </div>
          </div>
          <div class="leftbox">
            <h2 class="title"><span>TORQUYA</span><br>HOTEL</h2>
            <p class="desc">pick your perfect <span>bouquet</span></p>
            <img class="flower smaller" src="/static/images/login-img.jpeg" border="0">
            <p class="account">have an account?</p>
            <button class="button" id="signin">login</button>
          </div>
          <div class="rightbox">
            <h2 class="title"><span>TORQUYA</span><br>HOTEL</h2>
            <p class="desc"> pick your perfect <span>stay</span></p>
            <img class="login-img" src="/static/images/login-img.jpeg"/>
            <p class="account">don't have an account?</p>
            <button class="button" id="signup">sign up</button>
          </div>
        </div>
       </div>
    </div>
</body>
</html>

Hotel project/TorquayHotel_root/visitors/templates/reservation.html
<!DOCTYPE html>
<html>
<head>
    <title>Reservation</title>
</head>
<body>
    <h1>Reservation Details</h1>
    <p>Room: {{ room }}</p>
    <p>Check-in date: {{ check_in_date }}</p>
    <p>Check-out date: {{ check_out_date }}</p>
    <p>Number of guests: {{ num_guests }}</p>
    <p>user_name: {{ user }}</p>

    <h2>Guest Details</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
      </form>
</body>
</html>

Hotel project/TorquayHotel_root/visitors/templates/rooms.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/rooms.css' %}">
</head>
<body>
    <div class="content rooms-content">
            <span>
                <i class="fa-solid fa-angle-left" style="color: #ffffff; color: black;"></i>
                <i class="fa-solid fa-angle-right" style="color: #ffffff; color:  black;"></i>
            </span>
            <a href="#" class="content">Room1</a>
            <a href="#" class="content">Room1</a>
            <a href="#" class="content">Room1</a>
            <a href="#" class="content">Room1</a>
            <a href="#" class="content">Room1</a>
      </div>

      <script src="https://kit.fontawesome.com/c7bb54256c.js" crossorigin="anonymous"></script>
</body>
</html>

Hotel project/TorquayHotel_root/visitors/templates/test.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/test.css' %}">
</head>
<body>


<!-- first page -->
    <section class="first">
        <header>
            <nav class="navbar">
                <a href="#" class="logo">Torquay</a>
                <ul class="nav-links">
                  {% if user.is_authenticated %}
                    <h2 style="padding-right: 1.5rem;">Welcome, {{ user.username }}</h2>
                    <li><a href="{% url 'visitors:logout' %}">Logout</a></li>
                  {% else %}
                    <li><a href="{% url 'visitors:signup' %}">Register</a></li>
                    <li><a href="{% url 'visitors:login' %}">Login</a></li>
                  {% endif %}
                    <li><a href="#">EN</a></li>
                    <li><a href="{% url 'visitors:check_availability' %}">BOOK NOW</a></li>
                    <a href="#" class="menu-link" id="toggleMenu">Menu</a>
                </ul>
            </nav>
        </header>

        <!-- ==================sidenav=========== -->

        <div class="sidenav rev-block-left" id="sidenav">

            <ul class="sidenavbar">
                <li><a href = "#">Torquay Boutique</a></li>
                <li><a href = "#">Rooms</a></li>
                <li><a href = "#">Offers</a></li>
                <li><a href = "#">Dining</a></li>
                <li><a href = "#">Spa</a></li>
                <li><a href = "#">Experiencies</a></li>
                <li><a href = "#">Meetings&Events</a></li>
                <li><a href = "#">Gallery</a></li>
                <li><a href = "#">Contact us</a></li>
            </ul>

            <div class="follow-wrapper">
                <span>Follow us</span>
                <a href="#"><i class="fa-brands fa-facebook" style="color: #ffffff;"></i></a>
                <a href="#"><i class="fa-brands fa-instagram" style="color: #ffffff;"></i></a>
                <a href="#"><i class="fa-brands fa-tiktok" style="color: #fcfcfd;"></i></a>
            </div>
        </div>


        <div class="sidenav2 rev-block-right" id="sidenav2">
            <a href="#" class="menu-link-close" id="toggleClose">Close</a>
            <img class="sidenav-img" alt ='' src="/static/images//tdyfugh.jpeg">
            <span>Double Room</span>
        </div>


        <!-- ============end of sidenav============= -->

        <div class="main">
            <main>
                <h3 class="slogan">Your new Boutique Hotel in Torquay</h3>
            </main>
        </div>
    
        
        <div class="booking-line">
            <a href="#" class="link-with-form">
                No. of guests <i class="fa-solid fa-caret-down" style="color: #fafafa;"></i></a>
            <span>from</span>
            <a href="#" class="link-with-form">
                16 June <i class="fa-solid fa-caret-down" style="color: #ffffff;"></i></a>
            <span>to</span>
            <a href="#" class="link-with-form">
                Select date  <i class="fa-solid fa-caret-down" style="color: #ffffff;"></i></a>
            <a href="#" class="link-with-form">Check Availability</a>
        </div>

    </section>

<!-- second page -->

    <section>
        <div class="upper-section">
            <div class="column-title">
              <h2>Welcome to Torquay</h2>
            </div>
            <div class="column-text">
              <p>An enchanting coastal town, nestled amidst breathtaking landscapes, and adorned with timeless charm. Immerse yourself in our tranquil haven, designed for the discerning traveler and connoisseur. Experience a class beyond compare.</p>
            </div>
          </div>
    
          <div class="grid-container">
            <div class="grid-item v-stretch">
              <img src="/static/images/Swiss+Alps+Photographer+Murren+Fotomagoria+24 (1).jpg" alt="Image 1">
              <a href="#" class="content">Arrival and Contacts</a>
            </div>
            <div class="grid-item image">
              <img src="/static/images/torquya/image-asset.jpeg" alt="Image 2">
              <a href="#" class="content">Experiences</a>
            </div>
            <div class="grid-item v-stretch">
              <img src="/static/images/dining/3.webp" alt="Image 3">
              <a href="#" class="content">Dining</a>
            </div>
            <div class="grid-item image">
                <iframe width="100%" height="100%" src="https://www.youtube.com/embed/br3ig82_SgI?autoplay=1&mute=1&loop=1" frameborder="0" allowfullscreen></iframe>
                <a href="#" class="content">Spa</a>
            </div>
            <div class="grid-item big-stretch">
              <img src="/static/images/meetings/elmoderne-hotel-gijon-sala-de-reuniones-model-U.jpg" alt="Image 5">
              <a href="#" class="content">Conference</a>
            </div>
          </div>
    </section>      

<!-- third page -->

    <section>
      <div class="upper-section">
          <div class="column-title">
            <h2>Dining</h2>
          </div>
          <div class="column-text">
            <p>At the Torquay, dining is an artistic expression that knows no limits. Our culinary offerings embrace sensuality and variety, taking you on a gastronomic journey like no other. From homemade pizzas straight from the stone oven to avant-garde creations, we redefine the boundaries of taste and quality.</p>
          </div>
        </div>

        <div class="grid-container">
          <div class="grid-item v-stretch">
            <img src="/static/images/dining/1.jpg" alt="Image 1">
            <a href="#" class="content">Arrival and Contacts</a>
          </div>
          <div class="grid-item image">
            <img src="/static/images/dining/2.jpeg" alt="Image 2">
            <a href="#" class="content">Experiences</a>
          </div>
          <div class="grid-item v-stretch">
            <img src="/static/images/dining/6.webp" alt="Image 3">
            <a href="#" class="content">Dining</a>
          </div>
          <div class="grid-item image">
              <iframe width="100%" height="100%" src="https://www.youtube.com/embed/br3ig82_SgI?autoplay=1&mute=1&loop=1" frameborder="0" allowfullscreen></iframe>
              <a href="#" class="content">Spa</a>
          </div>
          <div class="grid-item big-stretch">
            <img src="/static/images/dining/5.jpg" alt="Image 5">
            <a href="#" class="content">Conference</a>
          </div>
        </div>

    </section>
        

<!-- =================4 page - ROOMS SECTION================== -->
        <section>
          <div class="upper-section">
              <div class="column-title">
                <h2>Rooms</h2>
              </div>
              <div class="column-text">
                <p>Experience luxurious comfort and impeccable style in our exquisite rooms. Each room is meticulously designed to provide a serene and inviting atmosphere for your stay. From spacious suites to cozy retreats, our accommodation options cater to every traveler's needs.</p>
              </div>
            </div>
      
            <div class="grid-container-rooms">
              <div class="room-item">
                <img class="slide1" src="/static/images/rooms/7132-hotel-scenic_retreats-vals-hotel-5s-double_room-20230116-357a9096.webp" alt="Room 1">
                <div class="room-content">
                    <div class="arrows">
                      <a a href="#" class="arrow arrow-left"><i class="fa-solid fa-angle-left fa-lg"></i></a>
                      <a href="#" class="arrow arrow-right"><i class="fa-solid fa-angle-right fa-lg"></i></a>
                    </div>
                    <a href="{% url 'visitors:rooms_page' %}" class="content">Double</a>
                    <a href="#slide2" class="content">Double Loft</a>
                    <a href="#slide3" class="content">Unique Junior Suit</a>
                    <a href="#slide4" class="content">Unique Junior Loft Suit</a>
                  </div>
                </div>
              </div>  
         </section>

         <!-- newsletter section -->

         <div class="newsletter">
            <h2 class="title">Newsletter</h2>
            <div class="form-wrapper">
                <div class="form-field">
                <input type="text" class="name" name="name" placeholder="Name">
                <input type="email" class="email" name="email" placeholder="Email">
                </div>
                <button class="subscribe-btn">Subscribe</button>
            </div>
          
            <div class="checkbox-wrapper">
                <input type="checkbox" id="checkbox" name="vehicle1" value="Bike">
                <label for="checkbox">I have read and accept the data protection law *</label><br>
            </div>
         </div>


         <!-- ==================Footer================ -->

         <footer>
            <hr>
            <div class="row">
                <div class="socials">
                    <a href="#" class="footer-link">Facebook</a>
                    <a href="#" class="footer-link">Instagram</a>
                    <a href="#" class="footer-link">TikTok</a>
                </div>
                <div class="info">
                    <a href="#" class="footer-link">+ 123456789</a>
                    <a href="#" class="footer-link">info@example.com</a>
                    <a href="#" class="footer-link">123 Street, Torquay</a>
                </div>
            </div>
        </footer>

    <script src="https://kit.fontawesome.com/c7bb54256c.js" crossorigin="anonymous"></script>

<!-- Include the JavaScript code -->
<script>
    const menuLink = document.getElementById('toggleMenu');
    const sidenav = document.getElementById('sidenav');
    const sidenav2 = document.getElementById('sidenav2');
    const toggleClose = document.getElementById('toggleClose');
  
    menuLink.addEventListener('click', function(event) {
      event.preventDefault();
      sidenav.classList.add('visible');
      sidenav2.classList.add('visible');
    });
  
    toggleClose.addEventListener('click', function(e) {
      e.preventDefault();
      sidenav.classList.remove('visible');
      sidenav2.classList.remove('visible');
    });
  
    // Add event listener to the document to handle clicks outside the menu
    document.addEventListener('click', function(event) {
      const target = event.target;
      if (!target.closest('#sidenav') && !target.closest('#sidenav2') && !target.matches('#toggleMenu')) {
        sidenav.classList.remove('visible');
        sidenav2.classList.remove('visible');
      }
    });
</script>

  
  
  
</body>
</html>